### ISSUE TITLE
Can't load complex .proto

### ISSUE THREAD

**Issue by diogorib94** [traveltime-dev/xk6-protobuf#5]
Hello,

We were trying to use xk6 for our performance tests and encountered this extension for protobuf.

When I try to load a complex object that has imports from another folder we always get "could not resolve import"
We tried to load all the files with protobuf.load(["folder1/file1.proto","folder2/file2.proto"]) but get the same error.

We also tried to merge all the .proto files to one but as the files have the same values for Enums we gave up on this

Do you know any workaround for this?

Thank you :)

**Comment by arnasbr** [comment]
Potential fix: https://github.com/traveltime-dev/xk6-protobuf/pull/6
